```{r}
#load all the necessary libraries
library(stringr)
library(readxl)
library(dplyr)
```

```{r}
#load all the necessary datasets
reviews <- read.csv("../dataset/disneyreviews.csv")
movies <- read.csv("../dataset/DisneyMoviesDataset.csv")
```

```{r}
#clean the Box.office column, remove the words "millions" and then convert the numbers to numeric (from text/character)

# Remove unnecessary columns
movies <- movies %>%
  select(-c(`X`, `Running.time..int.`, `Budget..float.`, `Box.office..float.`, 
            `Release.date..datetime.`, Traditional, Simplified))

# Fix column names
colnames(movies) <- gsub("\\.", "_", tolower(colnames(movies)))

# Handle missing values
# Fill missing numeric columns with 0 or appropriate values
movies$budget <- as.numeric(gsub("[^0-9]", "", movies$budget))
movies$box_office <- as.numeric(gsub("[^0-9]", "", movies$box_office))

# Convert `release_date` to Date format
movies$release_date <- str_extract(movies$release_date, "\\d{4}")
movies$release_date <- as.Date(paste(movies$release_date, "-01-01", sep=""))

clean_running_time <- function(rt) {
  # Extract numeric values from the string
  times <- as.numeric(unlist(str_extract_all(rt, "\\d+")))
  
  # Remove values greater than 999 (likely to be years)
  times <- times[times <= 999]
  
  # Calculate the average of the remaining values
  avg_time <- mean(times, na.rm = TRUE)
  
  return(avg_time)
}

# Apply the cleaning function to the running_time column
movies$running_time <- sapply(movies$running_time, clean_running_time)

# Final cleaned data
movies_cleaned <- movies%>%
  filter(!is.na(title)) %>% mutate(imdb = as.numeric(as.character(imdb)), 
                                    metascore = as.numeric(as.character(metascore)),
                                    rotten_tomatoes = as.numeric(gsub("%", "", rotten_tomatoes)))

# Display the cleaned data
head(movies_cleaned)

# Save the cleaned data to a new CSV file
write.csv(movies_cleaned, "../dataset/Cleaned_DisneyMoviesDataset.csv", row.names = FALSE)
```